[package]
name = "docufort"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reed-solomon = "0.2.1"
zstd = "0.12.4"

[dev-dependencies]
blake3 = "1.2.0"

[features]
ecc_len_2 = []
ecc_len_4 = []
ecc_len_6 = []
ecc_len_8 = []
ecc_len_16 = []
ecc_len_32 = []
default = ["ecc_len_4"]
